# This is a basic workflow to help you get started with Actions

name: Build

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout Repo

      - name: Run NPM Install
        run: |
          npm ci
      
      - name: Run NPM Build
        run: | 
          npm run build --if-present

      - name: Run NPM Test
        run: |
          npm run test
